server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      influx:
        enabled: false
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: springboot-promethues
