server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    export:
      influx:
        enabled: false
  endpoint:
    prometheus:
      enabled: true
