spring:
  datasource:
    password: "123"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://192.168.30.102:3306/flink"
    username: "root"


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none