spring:
  datasource:
    url: jdbc:mysql://192.168.30.102:3306/flink?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:/mapper/*
server:
  port: 8090


api-url: /api
